CREATE TABLE usuarios(id_Usuarios INT AUTO_INCREMENT NUll,
Nombre VARCHAR(55) NOT NULL, 
Apellidos  VARCHAR(55) NOT NULL, 
Direccion TEXT NOT NULL,
Telefono VARCHAR(55) NOT NULL,
FechaN DATE NOT NULL,
Email  VARCHAR(255) NOT NULL,
PRIMARY KEY (id_Usuarios)

) ENGINE = INNODB;

CREATE TABLE Plantel(id_Plantel INT AUTO_INCREMENT NOT NULL,
NombrePlantel  VARCHAR(55) NOT NULL,
clavep VARCHAR(55) NOT NULL,
Direccion  TEXT NOT NULL,
Telefono VARCHAR(15) NOT NULL,
Responsable  VARCHAR(55) NOT NULL,
PRIMARY KEY (id_Plantel)
) ENGINE = INNODB;

CREATE TABLE Lugar(id_L INT AUTO_INCREMENT NOT NULL,
NombreL VARCHAR(55) NOT NULL,
Descripcion TEXT NOT NULL,
Telefono VARCHAR(55) NOT NULL,
Email VARCHAR(55) NOT NULL,
Facebook VARCHAR(55) NOT NULL,
Horario DATE NOT NULL,
PRIMARY KEY (id_L)
) ENGINE = INNODB;
